#!/usr/bin/env bash

RSTUDIO_DIR="/Applications"
RSTUDIO_APP="RStudio.app"

ln -sf ./custom_styles.css \
    "$RSTUDIO_DIR/$RSTUDIO_APP/Contents/Resources/www/custom_styles.css"

ln -sf ./index.htm \
    "$RSTUDIO_DIR/$RSTUDIO_APP/Contents/Resources/www/index.htm"
